### ISSUE TITLE
Doesn't work on macOS. Could it be made cross-platform?

### ISSUE THREAD

**Issue by mukul-mehta** [nightroman/PS-GuiCompletion#4]
Hey! Thank you for this tool. I've been wanting to use it on a macbook but it doesn't work. I've attached 2 screenshots, with the command run and the error

![image](https://user-images.githubusercontent.com/43145555/119645215-6d3d1680-be3b-11eb-9674-d8aa7819aced.png)

![image](https://user-images.githubusercontent.com/43145555/119645276-7e862300-be3b-11eb-9297-0c2d72158781.png)

**Comment by nightroman** [comment]
PSGuiCompletion is Windows only, realistically speaking. It's sad, indeed. But this is not going to change, more likely.

In fact, it all depends on a terminal, PS host implementation, and maybe something else, too. So we cannot claim "PSGuiCompletion cannot work on non Windows platforms".

- https://github.com/cspotcode/PS-GuiCompletion/issues/13
- https://github.com/cspotcode/PS-GuiCompletion/issues/15

I close the issue, there is not much to do about it...

**Comment by mukul-mehta** [comment]
Ah, that's sad indeed
