### ISSUE TITLE
Scrolling down to shorter items does properly erase earlier text

### ISSUE THREAD

**Issue by sba923** [nightroman/PS-GuiCompletion#6]
_(Running 0.11.1 with PowerShell 7.2.6 in Windows Terminal Preview 1.15.2003.0)_

This should speak for itself:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/12860484/185374874-0fbb6e05-49bd-44f6-a025-e4a2a9d25479.png">

When scrolling down from `Start-MpRollback` to the next entry i.e. `Start-MpScan` the string `back` gets duplicated to every subsequent line...

**Comment by nightroman** [comment]
@sba923 Ha-ha, what a coincidence! The bug is there for ages. But exactly today I notice and fix this and you report as well. The fix is coming later today.

**Comment by nightroman** [comment]
In my case the bug shows slightly differently. But I think (and hope) it's the same bug.

![image](https://user-images.githubusercontent.com/927533/185379351-b0a69913-99ff-4429-82b5-03b2f5b112ea.png)

**Comment by nightroman** [comment]
The fix is in. Please let me know if it works for you, too.

**Comment by sba923** [comment]
Problem fixed by 1.0.0

You should compete for the fastest bugfix 😜

Thanks a bunch!
