### ISSUE TITLE
[Feature]List Rollover

### ISSUE THREAD

**Issue by hierfer** [nightroman/PS-GuiCompletion#7]
# Breif

Hope tab candidate list can rollover.

# Discription

Tab at last item jump back to the first. Vice versa. Many shell's completion can rollover the list, like this in zsh

![ls_completion_zsh](https://user-images.githubusercontent.com/14802836/218303090-f33d5560-b27f-4943-b1ec-5f0d6d79db6e.gif)

And tab + shift can select back, yet it's tiresome(press two keys). 

# Related

* Why this feature is not implemented? It seems a very natural function of completion, is there technical troubels?

**Comment by nightroman** [comment]
If this is really the standard and expected behaviour we probably may implement it.

Why was not it originally implemented this way? I cannot really tell. Frankly, I never thought of the original behaviour as wrong or inconvenient.

**Comment by hierfer** [comment]
It's not as serious as a right or wrong behaviour. I use zsh everywhere, guess just list rollover is natural for me. And yes, I'd like to say if rollover provided(as an option?), it'd be convenient for me(Willing tab ten times, instead of hold shift for a second==). 

ps: I use this module so very lot, thanks your great work.

**Comment by nightroman** [comment]
FWIW, I usually use arrow up/down and page up/down keys, much less tab, and never shift-tab.

**Comment by nightroman** [comment]
I think roll over will be confusing with many items (several pages). Without the scrollbar there will be no visual indication that you hit the bottom or top of the list. With the current behaviour it's quite visual, navigation stops there.

**Comment by hierfer** [comment]
Well, tab is more handy, or right hand gonna move to arrow keys when typing which is further without key remapping.

I think the jump action form the last to first item would be obvious enough to indicate that rollover happend. And this feature can be implemented as non-default option for those who'd like to use.

Zsh guys like me may acquainted list rollover more. Since thers's no technical trouble, I'd implement it for personal usage first. Then if you agree to add this feature a PR will raise.

**Comment by nightroman** [comment]
NB It looks like the scrollable list of suggestions is on the PSReadLine radars. If it is reasonably good then 
PS-GuiCompletion may become not needed.

https://devblogs.microsoft.com/powershell/psreadline-2-3-0-beta0-release/

**Comment by hierfer** [comment]
Readline functionality is almost as complete as **PS-GuiCompletion**. Yet can not tab is a problem under `ListView` mode of **Readline**. If simply change list pick key to tab, the basic completion would be blocked. Sure for rollover it got it. Let's consider it as a replacement.
